AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple hello world function.
Resources:
  hello:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: A simple hello world function.
      MemorySize: 512
      Timeout: 10
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /hello
            Method: ANY
